sonarqube:
  image: sonarqube:4.5.6
  ports:
    - "9000:9000"
    - "9002:9002"
    - "5432:5432"
  environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar

db:
  image: postgres
  net: container:sonarqube
  environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar

